# Generated by Django 6.0.5 on 2026-06-11 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_expiry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='action',
            field=models.CharField(choices=[('SALE', 'Sale'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('RESTOCK', 'Restock'), ('DAMAGE', 'Damaged/Expired'), ('AUDIT_CORRECTION', 'Audit Correction')], default='SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
