# Generated by Django 6.0.5 on 2026-06-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='action',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Manual Adjustment'), ('DELETE', 'Delete')], default='SALE', max_length=20),
        ),
    ]
